### ISSUE TITLE
Improve metastore for git-related workflows

### ISSUE THREAD

**Issue by przemoc** [przemoc/metastore#11]
This issue is for discussing what needs to be improved in metastore to make git users more happy.
- [ ] Textual metadata format (go to issue #6)
- [x] Remove empty directories (go to issue #10)
- [ ] More documentation with exemplary hooks? (go to issue #33)
